"""
Content for the ten service pages.

Everything here explains the trade. Nothing here invents a fact about the
business: no prices, no dates, no certifications, no client names, no counts.
"What determines the price" deliberately explains the variables, never figures.
"""

SERVICES = [

# ---------------------------------------------------------------- 1
dict(
 slug="property-maintenance-limerick",
 title="Property Maintenance Limerick &amp; Kerry | Repairs &amp; Planned Upkeep | Greenway",
 desc="Planned and reactive property maintenance across Limerick and Kerry. Repairs, handyman work and 24/7 emergency call-outs. One contractor for every trade.",
 h1="Property maintenance",
 lede="Planned and reactive maintenance for landlords, businesses and homeowners across Limerick and Kerry - coordinated through one number.",
 poster="photo-office",
 situation=[
   ("Buildings do not fail on a schedule",
    "A blocked gully in October. A failed socket the week a tenant moves in. A car park that has quietly worn through to the base course. The work is constant and it rarely arrives one job at a time - which is why the hard part is almost never the repair itself, it is finding someone who will take responsibility for all of it and turn up when they said they would."),
   ("Planned work is the cheap kind",
    "Almost every expensive repair started as a cheap one that nobody got to. Gutters clear before autumn, exterior paint renewed before the weather gets behind it, line markings refreshed before they fade to nothing. Planned preventative maintenance is unglamorous and it is where the money is saved."),
   ("Reactive work is the other half",
    "Then there is what you cannot plan for. Escaping water, storm damage, a break-in repair, anything that makes a property unsafe or unlettable. Emergency call-outs are available 24/7, and for those the phone is always faster than a form."),
 ],
 signs=["The same small defect has been on your list for more than a season",
        "You are managing three or four different trades yourself",
        "A tenant or member of staff has reported the same fault twice",
        "You have a property standing empty between lettings",
        "Something has failed and it cannot wait until Monday"],
 method=[("Describe it once", "One call or one form. You do not have to diagnose it for us."),
         ("We come and look", "A free site visit and assessment. If it needs more than one trade, we scope all of them."),
         ("One itemised quote", "Every trade on one document, so you can see what you are paying for and why."),
         ("We sequence and supervise", "Trades arrive in the right order. You are not the one chasing the plasterer."),
         ("Final walkthrough", "We go through the finished work with you before we call it done.")],
 price_factors=[
   ("Access", "How easily materials, machinery and people reach the work. A back garden reached through a house costs more than a driveway you can park on."),
   ("What is behind it", "Opening up a wall or lifting a floor sometimes reveals the actual problem. A good quote says what happens if it does."),
   ("Whether it is one trade or four", "Coordinated multi-trade work carries scheduling cost, but far less than the delay of running them yourself."),
   ("Planned versus emergency", "Scheduled work is always cheaper than a call-out at 2am. That is not a surcharge, it is the cost of dropping everything."),
   ("Materials and specification", "Like-for-like replacement versus an upgrade. We will tell you where spending more actually lasts longer and where it does not."),
 ],
 not_needed="If your problem is a single, simple fault and you already have a trusted tradesperson for it, use them. We are worth calling when the job spans trades, when nobody will take ownership of the whole thing, or when you have run out of patience chasing people. We would rather tell you that than quote for work you do not need.",
 scope=["General repairs and handyman work", "Planned preventative maintenance",
        "24/7 emergency call-outs", "Structural repairs", "Door and window repairs",
        "End-of-tenancy make-good", "Multi-trade project coordination"],
 faq=[("Do you cover Kerry as well as Limerick?",
       "Yes. We are based in Ardagh, Co. Limerick and work throughout the county and into Kerry, including Tralee, Listowel, Castleisland and the surrounding areas."),
      ("Do you take on small jobs?",
       "Yes. There is no minimum job size, and quotes are free whether the job is an afternoon or a full refurbishment."),
      ("How quickly can you attend an emergency?",
       "Emergency call-outs are available 24/7. Call rather than emailing for anything urgent - it is the fastest route to us."),
      ("Do you charge for quotes or site visits?",
       "No. Site visits, assessments and written quotes are free and carry no obligation."),
      ("Can you work around a business that has to stay open?",
       "Yes. Commercial work is routinely phased or scheduled outside trading hours so the premises keeps operating.")],
),

# ---------------------------------------------------------------- 2
dict(
 slug="grounds-maintenance-limerick",
 title="Grounds Maintenance &amp; Grass Cutting, Limerick &amp; Kerry | Greenway",
 desc="Grounds maintenance across Limerick and Kerry - grass cutting, hedge trimming, weed control and seasonal clean-ups. One-off visits or ongoing contracts.",
 h1="Grounds maintenance",
 lede="Grounds kept presentable all year for business parks, estates and private properties across Limerick and Kerry.",
 poster="photo-grounds",
 situation=[
   ("Grounds are the first thing anyone reads",
    "Overgrown grass, straggling hedges and weeds through the paving say something about a building before anyone reaches the door. It is the cheapest impression a premises makes, and the easiest one to lose."),
   ("Consistency beats intensity",
    "Grounds that get cut whenever someone remembers spend half the year looking neglected. A scheduled visit costs less per year than the occasional emergency blitz, and the site never drops below presentable."),
   ("The Irish growing season is not gentle",
    "Growth here is fast and long. Frequency needs to rise through spring and summer and taper into autumn - a fixed monthly visit either wastes money in winter or loses control in June."),
 ],
 signs=["Grass is being cut reactively rather than on a schedule",
        "Hedges have outgrown their intended line",
        "Weeds are coming through paving, kerbs or gravel",
        "A property is being prepared for sale or letting",
        "Leaves are blocking gullies every autumn"],
 method=[("Walk the site", "We look at what is actually there - aspect, drainage, access, what is growing and how fast."),
         ("Agree a frequency", "Set to the site and the season, not a flat number that suits us."),
         ("Cut, trim, control", "Grass, hedges, edges and weed control on each visit."),
         ("Clear as we go", "Arisings removed unless you would rather they stayed on site."),
         ("Seasonal work", "Autumn clear-downs and spring resets folded into the schedule.")],
 price_factors=[
   ("Area and terrain", "Flat open lawn cuts far faster than banks, awkward corners and obstacles."),
   ("Frequency", "More frequent visits cost less each, because there is less growth to fight."),
   ("Hedging", "Height and length matter, and whether we need access equipment to reach the top safely."),
   ("Waste", "Removing arisings costs more than leaving them; on larger sites it is often the biggest single variable."),
   ("Condition at the start", "A site that has been let go needs a clearance before a maintenance schedule can begin. That is a one-off cost, not the ongoing rate."),
 ],
 not_needed="If you have a small domestic lawn and a working mower, you do not need a contractor - you need a dry Saturday. Grounds maintenance earns its cost on commercial sites, larger properties, rentals, or where you simply are not there often enough to keep on top of it.",
 scope=["Grass cutting and lawn maintenance", "Hedge trimming and shaping", "Weed control",
        "Seasonal clean-ups", "Site and garden clearance", "Leaf and gully clearing",
        "Ongoing grounds maintenance contracts"],
 faq=[("Do you offer ongoing contracts?",
       "Yes. Contracts are common for business parks, estates and commercial properties, with visit frequency set to the site and the season."),
      ("Will you take on a site that has been let go?",
       "Yes. Overgrown clearances are routine, including vacant properties and land being prepared for sale."),
      ("Do you remove the cuttings?",
       "Yes, unless you would prefer them left on site - some clients want them retained."),
      ("Do you cover Kerry?",
       "Yes, across Limerick and into Kerry."),
      ("Can you work outside business hours?",
       "Yes, where a site needs it.")],
),

# ---------------------------------------------------------------- 3
dict(
 slug="drain-cleaning-limerick",
 title="Drain Cleaning &amp; Drainage, Limerick &amp; Kerry | Blocked Drains | Greenway",
 desc="Drain cleaning, unblocking and drainage repair across Limerick and Kerry. Gully cleaning, CCTV surveys and surface water management. 24/7 call-outs.",
 h1="Drainage &amp; gullies",
 lede="Blockages cleared, gullies maintained and surface water managed - for commercial and residential property across Limerick and Kerry.",
 poster="photo-drainage",
 situation=[
   ("A blockage is a symptom, not the story",
    "Clearing it gets the property working again tonight, and sometimes that genuinely is the whole job. But if the same gully backs up every autumn, or a section of pipe has collapsed or bellied, then clearing it again next year is money you are spending twice."),
   ("Surface water does most of the damage",
    "Ireland does not lack rainfall. Blocked gullies, silted channels, shallow falls and undersized outfalls all end the same way - water going somewhere it should not, usually into a building. Most of it is preventable with maintenance that costs a fraction of the damage."),
   ("Autumn is the deadline",
    "For commercial sites, scheduled gully and channel cleaning before leaf fall is dramatically cheaper than an emergency call-out and a flooded unit in November."),
 ],
 signs=["The same drain blocks more than once a year",
        "Water stands on the surface after ordinary rain",
        "Gullies are visibly silted or full of leaves",
        "Smells from drains inside or outside the building",
        "Slow draining across several fixtures at once, not just one"],
 method=[("Clear the immediate problem", "Get the property functioning first."),
         ("Establish whether it will recur", "If the history suggests a defect, we say so rather than leaving you to find out."),
         ("Survey if it is warranted", "A CCTV survey shows exactly what is happening underground - root ingress, collapse, belly, or simply silt."),
         ("Repair the cause", "Relining or excavation and replacement, scoped to what the survey found."),
         ("Set a maintenance interval", "Where silt or leaves are the real driver, scheduled cleaning is the fix.")],
 price_factors=[
   ("Whether it is a clear or a repair", "Jetting a blockage and excavating a collapsed pipe are different orders of work."),
   ("Access and depth", "A gully in an open yard is straightforward. A run under a building or a finished driveway is not."),
   ("Whether a survey is needed", "Surveys cost money and are not always justified - for a first-time blockage with an obvious cause, often they are not."),
   ("Reinstatement", "If we have to break out tarmac or paving, putting it back properly is part of the job and part of the price."),
   ("Emergency versus scheduled", "Out-of-hours attendance costs more, which is precisely why planned gully cleaning is worth scheduling."),
 ],
 not_needed="If a single sink or toilet is slow and everything else drains normally, the problem is almost certainly local to that fixture, not your drainage system - a plunger or a plumber will be cheaper and faster than us. Call us when the problem is outside, recurring, or affecting more than one fixture.",
 scope=["Drain cleaning and unblocking", "Emergency blocked-drain call-outs",
        "Gully and channel cleaning", "CCTV drain surveys", "Drain repairs and relining",
        "Storm and surface water management", "Planned gully maintenance contracts"],
 faq=[("Do you attend emergencies?",
       "Yes, 24/7. For flooding or sewage backing up, call rather than using the form."),
      ("Why does the same drain keep blocking?",
       "Recurring blockages usually mean an underlying defect - root ingress, a collapsed or bellied section, heavy silt, or a fall that is too shallow. A CCTV survey identifies which."),
      ("Do you do scheduled gully cleaning for commercial sites?",
       "Yes, and for most sites the sensible interval is before autumn."),
      ("Do you cover rural properties?",
       "Yes, throughout Limerick and Kerry including rural areas."),
      ("Will you have to dig up the driveway?",
       "Not usually. Many defects can be relined without excavation. If digging is genuinely necessary we will explain why before anything starts.")],
),

# ---------------------------------------------------------------- 4
dict(
 slug="tarmacadam-limerick",
 title="Tarmacadam &amp; Surfacing, Limerick &amp; Kerry | Driveways &amp; Car Parks | Greenway",
 desc="Tarmacadam surfacing across Limerick and Kerry - driveways, car parks, private roadways and pothole repairs. Full groundworks through to finished surface.",
 h1="Tarmacadam &amp; surfacing",
 lede="Driveways, car parks, private roadways and yards across Limerick and Kerry - built from the base course up.",
 poster="photo-tarmac",
 situation=[
   ("A surface is only as good as what is under it",
    "Most failed driveways and car parks did not fail in the wearing course. They failed because the sub-base was never right, or because water had nowhere to go. Anyone can lay a black surface that looks correct for two summers."),
   ("Drainage is part of surfacing",
    "Falls, edges, gullies and outfalls are not extras. Water that cannot leave a surface gets underneath it, and once it is under the base in an Irish winter, freeze-thaw does the rest."),
   ("Not everything needs a full dig-out",
    "Where the base is genuinely sound, an overlay is far more economical. Where it has failed, laying new material over the problem simply buys you a year. Part of the job is telling you honestly which one you have."),
 ],
 signs=["Potholes reappearing in the same spots",
        "Standing water after ordinary rain",
        "Cracking that follows a pattern rather than one-off damage",
        "Edges crumbling where there is no kerb or restraint",
        "Trench scars from utility work that were never reinstated properly"],
 method=[("Assess the existing base", "This determines everything else, so it happens first."),
         ("Excavate and prepare", "Dig out to the depth the job actually needs, not the depth that is quickest."),
         ("Set falls and edges", "Drainage falls, kerbing and edge restraint before any surfacing."),
         ("Base and binder", "Laid and compacted in the correct sequence."),
         ("Wearing course", "Rolled to finish, then left to cure before traffic."),
         ("Mark out if required", "Line marking follows on directly where a car park needs it.")],
 price_factors=[
   ("Condition of the existing base", "Overlay versus full excavation is the single biggest cost difference in the job."),
   ("Area and depth", "Depth is dictated by use - a domestic driveway and a yard taking HGVs are not the same construction."),
   ("Drainage works", "Whether gullies, channels or falls need to be created or corrected."),
   ("Edging and kerbing", "Unrestrained edges fail first, so this is rarely worth cutting."),
   ("Access for plant", "Whether machinery can reach the area, and what has to be protected while it does."),
   ("Muckaway", "Excavated material has to go somewhere, and on larger digs that is a real line item."),
 ],
 not_needed="If your driveway is structurally sound and just looks tired, you may need a clean rather than a new surface - power washing costs a fraction of resurfacing. And if only a small area has failed, a patch repair is often the honest answer. We will say so.",
 scope=["Tarmacadam surfacing and resurfacing", "Car park construction and repair",
        "Driveways and parking aprons", "Private roadways and access roads",
        "Pothole repairs and patching", "Trench reinstatement",
        "Kerbing, edging and footpaths"],
 faq=[("How long does a driveway take?",
       "Most domestic driveways are a few days depending on size, groundworks and weather. We confirm a realistic timeframe in the written quote rather than an optimistic one."),
      ("Can you resurface over what is there?",
       "Often, yes - if the base is sound. If it has failed we will tell you, because an overlay over a failed base will not last."),
      ("How soon can we drive on it?",
       "New tarmac needs time to cure and the timeframe varies with weather and depth. We give you specific guidance on the day."),
      ("Do you do the line marking too?",
       "Yes. Surfacing and marking are frequently done together so the car park comes back into use fully finished."),
      ("Do you work in Kerry?",
       "Yes, across Limerick and Kerry.")],
),

# ---------------------------------------------------------------- 5
dict(
 slug="white-lining-car-park-markings-limerick",
 title="White Lining &amp; Car Park Markings, Limerick &amp; Kerry | Greenway",
 desc="Car park line marking across Limerick and Kerry - bay markings, accessible bays, arrows, hatching and road markings. Durable, compliant, minimal disruption.",
 h1="White lining &amp; car parks",
 lede="Line marking for car parks, business premises, schools and public areas across Limerick and Kerry.",
 poster="photo-tarmac",
 situation=[
   ("Markings are doing more work than they look",
    "Good layout maximises usable spaces, keeps traffic moving one way, keeps pedestrians away from reversing vehicles and makes accessible bays genuinely usable. A faded car park does the opposite - spaces get wasted, cars park at angles, and the site looks neglected before anyone reaches reception."),
   ("Re-marking is the cheapest improvement a premises can make",
    "Markings fade with traffic, weather and cleaning. Refreshing an existing layout is quick and inexpensive, and few things lift the look of a commercial property faster for the money."),
   ("Layout can be changed, not just repainted",
    "If the current arrangement no longer suits how the site is used, there is usually room to set out a better one - more spaces, safer circulation, or proper delivery access."),
 ],
 signs=["Bays are no longer clearly visible in the wet or at night",
        "Drivers are parking across lines or at inconsistent angles",
        "Accessible bays lack proper markings or hatched transfer space",
        "You have resurfaced and the markings have not been reinstated",
        "Traffic flow around the site causes near-misses"],
 method=[("Survey and set out", "Measure the site and confirm the layout before any paint."),
         ("Programme around you", "Sections, evenings or weekends so the premises keeps working."),
         ("Prepare the surface", "Markings only last if what is under them is clean and sound."),
         ("Apply", "Bays, arrows, hatching, accessible bays and any signage-linked markings."),
         ("Cure and hand back", "Sections reopened as they cure.")],
 price_factors=[
   ("Number and type of markings", "Straight bays are quick. Arrows, hatching, lettering and disabled symbols take longer."),
   ("New layout versus refresh", "Re-marking existing lines is faster than setting out a new arrangement from scratch."),
   ("Surface condition", "Paint on a failing or contaminated surface will not hold, so preparation can be a real part of the cost."),
   ("Paint system", "Different products suit different traffic loads and expected life."),
   ("Access and timing", "Out-of-hours or phased working to keep a site trading carries cost, but usually far less than closing."),
 ],
 not_needed="If your markings are simply dirty rather than worn, a clean may bring them back - worth checking before repainting. And if the surface underneath is breaking up, marking it now is money wasted; the surfacing should come first.",
 scope=["Car park bay markings", "Accessible and disabled bay markings",
        "Directional arrows and hatching", "No-parking and loading zones",
        "Road and access markings", "Line re-marking and refresh",
        "Numbering and reserved bays"],
 faq=[("How long before cars can use the bays?",
       "Curing depends on the paint system and the weather, but sections are typically usable the same day. We confirm timings on site so you can plan access."),
      ("Can you design a new layout?",
       "Yes - bay sizes, circulation, accessible bays and delivery access can all be set out fresh to make better use of the space."),
      ("Do you mark private roads and yards?",
       "Yes, including industrial yards, loading areas and internal site roads."),
      ("Can you work outside opening hours?",
       "Yes, and for schools and retail premises that is usually how it is scheduled."),
      ("Do you cover Kerry?",
       "Yes, Limerick and Kerry.")],
),

# ---------------------------------------------------------------- 6
dict(
 slug="power-washing-limerick",
 title="Power Washing, Limerick &amp; Kerry | Driveway &amp; Exterior Cleaning | Greenway",
 desc="Power washing across Limerick and Kerry - driveways, patios, paths, forecourts and building exteriors. Commercial and domestic.",
 h1="Power washing",
 lede="Driveways, patios, forecourts and building exteriors across Limerick and Kerry - years of growth removed in a visit.",
 poster="transition-tarmac",
 situation=[
   ("Irish surfaces grow a coat",
    "Algae, moss and dirt build within a couple of seasons here. It happens slowly enough that people stop noticing, until a strip gets cleaned and the difference is obvious."),
   ("It is a safety issue before it is a cosmetic one",
    "Moss-covered paving and steps get genuinely slippery in wet weather. On a commercial premises where the public walk, that matters considerably more than appearance."),
   ("Cleaning is often the alternative to replacing",
    "A surface that is dirty is not a surface that has failed. Cleaning costs a fraction of resurfacing, and on a sound driveway it is usually the right answer."),
 ],
 signs=["Paving has gone green, black or slick underfoot",
        "The colour of the original surface is no longer visible",
        "Moss is establishing in joints and along edges",
        "You are preparing a property for sale, letting or photography",
        "Bins, forecourts or entrances are letting down an otherwise tidy premises"],
 method=[("Identify the surface", "Different materials take different pressure and technique. Getting this wrong damages the surface."),
         ("Protect surroundings", "Planting, vents, doors and anything that will not thank you for a jet of water."),
         ("Clean", "Worked evenly so there are no stripes or missed edges."),
         ("Clear the residue", "Lifted growth and silt removed rather than left to wash into gullies."),
         ("Advise on sealing", "Where sealing is genuinely worthwhile for the surface, and where it is not.")],
 price_factors=[
   ("Area", "The obvious one, and usually the main one."),
   ("How bad it is", "Two seasons of algae and ten years of ingrained moss are different jobs."),
   ("Surface type", "Some materials need slower, gentler work, which takes longer."),
   ("Water and access", "Whether there is a supply on site and how far equipment has to reach."),
   ("Waste and drainage", "On larger commercial jobs, controlling and clearing residue is a real part of the work."),
 ],
 not_needed="If your driveway is cracked, sinking or breaking up, cleaning it will make the damage more visible rather than less - that is a surfacing job. And a small patio with a hose and a stiff brush is a morning's work you can do yourself. We are worth it for scale, for height, or where the surface needs care.",
 scope=["Driveway and patio cleaning", "Path and footpath cleaning",
        "Commercial forecourts and yards", "Building exterior and facade washing",
        "Bin store and loading area cleaning", "Pre-sale and end-of-tenancy exterior cleans"],
 faq=[("Will pressure washing damage my paving?",
       "Not when the pressure and technique suit the surface. Getting that judgement right is most of the skill, and we assess it on site."),
      ("How often should a driveway be cleaned?",
       "Most Irish driveways benefit every one to two years, depending on shade, tree cover and drainage."),
      ("Do you work outside business hours?",
       "Yes - commercial cleaning is frequently scheduled for evenings or weekends."),
      ("Should I have it sealed afterwards?",
       "Sometimes. It depends on the surface, and we will tell you when it is not worth the money."),
      ("Do you cover Kerry?",
       "Yes, Limerick and Kerry.")],
),

# ---------------------------------------------------------------- 7
dict(
 slug="painting-decorating-limerick",
 title="Painters &amp; Decorators, Limerick &amp; Kerry | Interior &amp; Exterior | Greenway",
 desc="Painting and decorating across Limerick and Kerry - interior and exterior, wallpapering and full surface preparation. Commercial and domestic.",
 h1="Painting &amp; decorating",
 lede="Interior and exterior decorating for homes, offices and commercial premises across Limerick and Kerry.",
 poster="photo-kitchen",
 situation=[
   ("Preparation is the job",
    "Anyone can apply paint. The difference between a repaint that still looks right in five years and one that flakes within two is almost entirely what happened before the first coat - filling, caulking, sanding, stabilising powdery surfaces, and treating damp or rot rather than sealing it in."),
   ("Exterior work here has a short weather window",
    "Persistent damp, wind-driven rain and unreliable dry spells affect product choice and timing as much as technique - particularly on fascias, soffits, render and whichever elevation takes the weather."),
   ("Commercial repaints do not have to close anything",
    "Offices, retail units and premises can be done in phases or outside trading hours. Most of the planning is about sequence, not paint."),
 ],
 signs=["Paint is flaking, chalking or blistering rather than just tired",
        "Filler and caulk lines are opening up around trim",
        "Exterior timber is starting to feel soft at the edges",
        "A property needs to present well for sale or letting",
        "Rooms were painted over damp and the marks keep returning"],
 method=[("Inspect and identify", "Including anything that is a repair rather than a decorating problem."),
         ("Protect and mask", "Floors, fittings and everything that is staying."),
         ("Prepare", "Fill, caulk, sand, stabilise. This is where the time goes."),
         ("Repair first", "Damaged plaster, rot and damp addressed before paint, not under it."),
         ("Coat properly", "Correct number of coats for the surface and product."),
         ("Clean up", "Site left usable, not just finished.")],
 price_factors=[
   ("Condition of the surfaces", "A sound wall needing two coats and a wall needing full preparation are different jobs at the same square metre."),
   ("Access and height", "Ladders, towers or scaffold for exterior and stairwell work."),
   ("Number of colours and cutting-in", "More colour changes and more detail means more time."),
   ("Interior versus exterior", "Exterior work carries weather risk and more preparation."),
   ("Out-of-hours working", "Evening or weekend commercial work to avoid disruption."),
   ("Specification", "Trade versus premium products - we will say where the upgrade actually lasts longer."),
 ],
 not_needed="If the surface is sound and you simply want a colour change in one room, that is a very doable weekend. Where we earn our money is preparation-heavy work, exteriors, height, and anything where the last paint job failed and nobody has established why.",
 scope=["Interior painting - walls, ceilings, woodwork", "Exterior painting and render coating",
        "Fascia, soffit and gutter painting", "Wallpaper hanging and removal",
        "Full surface preparation and repairs", "Commercial and office repaints"],
 faq=[("Do you do preparation or just paint?",
       "Preparation is included as standard - filling, caulking, sanding and repairing damaged plaster. It is not an optional extra."),
      ("Can you work outside business hours?",
       "Yes, commercial decorating is often scheduled for evenings or weekends."),
      ("Do you supply the paint?",
       "We can supply everything, or work with a specification you have already chosen."),
      ("What about damp patches that keep coming back?",
       "Those are a repair problem, not a paint problem. Painting over them wastes your money - we would look at the cause first."),
      ("Do you cover Kerry?",
       "Yes, Limerick and Kerry.")],
),

# ---------------------------------------------------------------- 8
dict(
 slug="carpentry-limerick",
 title="Carpenters, Limerick &amp; Kerry | Carpentry &amp; Joinery | Greenway",
 desc="Carpentry and joinery across Limerick and Kerry - doors, flooring, built-in storage, second fix and general building works.",
 h1="Carpentry &amp; joinery",
 lede="Doors, floors, built-in storage and second-fix work for homes and commercial property across Limerick and Kerry.",
 poster="photo-kitchen",
 situation=[
   ("Carpentry is unforgiving in a way other trades are not",
    "A door that binds. A floor that creaks in the same spot. A fitted unit a few millimetres out of square. These are the details people notice every single day, long after they have forgotten what the walls cost to paint."),
   ("Older Irish properties are rarely square",
    "Which is exactly why off-the-shelf units so often sit badly in them. Built-in work made to the actual opening solves problems that flat-pack cannot."),
   ("Second fix is where sequencing shows",
    "Carpentry is usually one element of a bigger job. Done in the wrong order - before plastering has dried, after decoration has finished - it costs twice."),
 ],
 signs=["Doors sticking, dropping or no longer latching",
        "Floors creaking, lifting or springing underfoot",
        "Gaps opening at skirting, architrave or stair strings",
        "Storage that does not fit the space it is in",
        "A refurbishment where trades keep arriving in the wrong order"],
 method=[("Measure the actual opening", "Not the nominal size. This is the whole difference in older buildings."),
         ("Confirm the sequence", "Where the carpentry sits relative to plastering, electrical and decoration."),
         ("Prepare the substrate", "Levels and fixings checked before anything is fitted."),
         ("Fit", "Hung, levelled, scribed and packed as the opening actually requires."),
         ("Finish", "Trim, adjust and leave it operating correctly, not just installed.")],
 price_factors=[
   ("Made to measure versus stock", "Bespoke costs more and is sometimes the only thing that will fit properly."),
   ("How square the building is", "Scribing to an out-of-true opening takes real time."),
   ("Materials", "Solid timber, engineered board and veneer differ substantially."),
   ("Whether other trades are involved", "Second-fix carpentry within a wider refurbishment needs coordination."),
   ("Finishing", "Whether the work is supplied primed, finished on site, or left for a decorator."),
 ],
 not_needed="Hanging a single internal door in a modern, square opening is a genuinely achievable DIY job, and we will not pretend otherwise. Bring us in for made-to-measure work, older properties where nothing is true, structural carpentry, or anything forming part of a multi-trade job.",
 scope=["Door hanging and replacement", "Timber and laminate flooring",
        "Built-in storage and wardrobes", "Skirting, architrave and second fix",
        "Stud partitions and framing", "General building and joinery works"],
 faq=[("Do you make built-in furniture to measure?",
       "Yes, and in older properties that is usually the only way to get a proper fit."),
      ("Do you fit flooring?",
       "Yes - timber and laminate, with the associated trim and threshold work."),
      ("Can you handle a full refurbishment?",
       "Yes. Because we coordinate the other trades, second-fix carpentry can be sequenced properly rather than squeezed in."),
      ("Do you do commercial fit-outs?",
       "Yes, including partitions, doors and second-fix works."),
      ("Do you cover Kerry?",
       "Yes, Limerick and Kerry.")],
),

# ---------------------------------------------------------------- 9
dict(
 slug="window-fitting-limerick",
 title="Window Fitting &amp; Repairs, Limerick &amp; Kerry | Double Glazing | Greenway",
 desc="Window installation, replacement and repair across Limerick and Kerry - double and triple glazing, locks, handles and draught proofing.",
 h1="Windows &amp; doors",
 lede="Installation, replacement and repair for homes and commercial premises across Limerick and Kerry.",
 poster="photo-office",
 situation=[
   ("Old windows are expensive to keep",
    "Failed or ageing units are one of the largest sources of heat loss in an Irish property, and one of the most obvious to live with - draughts, condensation between the panes, rooms that never quite warm up, and rattling every time the wind gets up."),
   ("Not everything needs replacing",
    "Failed locks, worn handles, dropped or misaligned sashes and perished seals are frequently repairable at a fraction of replacement cost. Replacing a whole unit because a mechanism failed is a common and expensive mistake."),
   ("Security is the quiet half of this",
    "Locks and handles are the part of a window most likely to be tested, and among the cheapest things to upgrade."),
 ],
 signs=["Condensation forming between the panes rather than on them",
        "A noticeable draught with the window fully closed",
        "The handle or lock no longer engages cleanly",
        "The sash has dropped and catches on the frame",
        "Timber frames soft or discoloured at the bottom corners"],
 method=[("Establish repair or replace", "Honestly. The cheaper answer is often the right one."),
         ("Survey the openings", "Every opening measured individually - assumptions cause problems here."),
         ("Protect the property", "Especially where a unit is out and the weather is not cooperating."),
         ("Remove and fit", "Squared, levelled, fixed and sealed correctly."),
         ("Seal and make good", "Internal and external finishing so there is no draught path left behind."),
         ("Check operation", "Every unit opened, closed and locked before we leave.")],
 price_factors=[
   ("Repair or replacement", "By far the biggest variable, and worth establishing before anything else."),
   ("Number and size of openings", "Larger units and non-standard shapes cost more."),
   ("Glazing specification", "Double versus triple, and the glass specification within that."),
   ("Frame material", "Different materials carry different cost and different lifespans."),
   ("Access", "Upper floors and awkward elevations may need access equipment."),
   ("Making good", "Whether internal finishes need repair after removal."),
 ],
 not_needed="If the only fault is a stiff handle, a failed lock or a draught around one frame, do not let anyone sell you a replacement window. Those are repairs, and we would rather do the repair than the replacement.",
 scope=["Window installation and replacement", "Double and triple glazing",
        "Repairs and adjustments", "Locks and handles", "Draught proofing",
        "Commercial glazing", "External door fitting"],
 faq=[("Can you repair instead of replacing?",
       "Very often, yes. Locks, handles, hinges, seals and alignment are usually repairable, and we will tell you when that is the better value option."),
      ("Do you fit double and triple glazing?",
       "Yes, for domestic and commercial properties."),
      ("How disruptive is a replacement?",
       "Most domestic jobs are a day or two depending on the number of units, and we clear up as we go rather than at the end."),
      ("Are there grants for this?",
       "Home energy grant schemes exist in Ireland and eligibility depends on the property and the works. We will tell you what appears to apply to your situation and point you at the official scheme - we do not administer grants."),
      ("Do you cover Kerry?",
       "Yes, Limerick and Kerry.")],
),

# ---------------------------------------------------------------- 10
dict(
 slug="commercial-cleaning-limerick",
 title="Commercial Cleaning, Limerick &amp; Kerry | Deep &amp; End-of-Tenancy | Greenway",
 desc="Commercial cleaning across Limerick and Kerry - deep cleans, end-of-tenancy, industrial cleaning, pressure washing and ongoing contracts.",
 h1="Commercial cleaning",
 lede="Deep cleans, end-of-tenancy and industrial cleaning for commercial and residential property across Limerick and Kerry.",
 poster="photo-cleaning",
 situation=[
   ("There is routine cleaning, and there is resetting a property",
    "Deep cleans, post-construction cleans and end-of-tenancy cleans are the second kind - getting a property back to lettable, saleable or handover condition. That is what we are usually called in for."),
   ("For landlords, the void is the cost",
    "The gap between tenancies is dead money. A thorough end-of-tenancy clean combined with whatever make-good repairs are needed gets a property back to market faster - and because we cover the trades too, the cleaning and the repairs can happen in one coordinated visit instead of three sequential ones."),
   ("Post-works cleaning is its own discipline",
    "Construction dust gets everywhere and keeps reappearing for weeks if the clean is done once and done badly. Warehouses and industrial units need different equipment again."),
 ],
 signs=["A property is between tenancies or going to market",
        "Building work has finished and dust keeps resettling",
        "Floors have lost their finish and no longer respond to routine cleaning",
        "A premises needs to present properly for an inspection or handover",
        "Routine cleaning is no longer keeping up with the site"],
 method=[("Walk it first", "Scope the actual condition rather than quoting off a floor area."),
         ("Sequence with any repairs", "If make-good work is needed, cleaning goes after it, not before."),
         ("Work top down", "So nothing lands on what has already been done."),
         ("Specialist equipment where needed", "Floor scrubbers, pressure washing, dust extraction."),
         ("Final inspection", "Walked with you, so handover is not a negotiation.")],
 price_factors=[
   ("Condition versus size", "Condition usually matters more than square metres."),
   ("Whether repairs are involved", "Coordinated clean-and-repair is more efficient than separate visits."),
   ("Specialist requirements", "Floor treatments, high-level access, industrial equipment."),
   ("One-off or contract", "Ongoing contracts price differently to a single deep clean."),
   ("Access and hours", "Out-of-hours access for occupied premises."),
 ],
 not_needed="If you have a regular cleaner keeping a premises in good order, you do not need us for routine work. Call us for the resets - end of tenancy, post-construction, or a property that has got beyond what routine cleaning can recover.",
 scope=["Deep cleaning", "End-of-tenancy cleaning", "Property clearances",
        "Industrial and warehouse cleaning", "Post-construction cleaning",
        "Pressure washing", "Ongoing commercial cleaning contracts"],
 faq=[("Do you do end-of-tenancy cleans for landlords?",
       "Yes, and because we also cover repairs and decoration, the make-good work can be coordinated in the same visit to shorten the void."),
      ("Do you offer ongoing contracts?",
       "Yes, arranged around the premises and its operating hours."),
      ("Can you clean after building work?",
       "Yes. Post-construction cleans including dust removal and floor treatment are routine."),
      ("Do you cover Kerry?",
       "Yes, Limerick and Kerry."),
      ("Can you work outside opening hours?",
       "Yes, and for occupied commercial premises that is usually preferable.")],
),
]
